name: BedWars
version: 0.7
main: me.camm.productions.bedwars.BedWars
authors: [CAMM_H87, Asdf_Noob]
description: A plugin for Bedwars.
commands:
  setup:
    usage: /setup
    description: performs setup operations on the arena
    permission: setup.do
    permission-message: You do not have permission to setup the arena
  register:
    usage: /register
    description: registers a or changes the team of a player
    permission: register.do
    permission-message: You do not have permission to join the game
  start:
    usage: /start
    description: attempts to start the game
    permission: game.do
    permission-message: you do not have permission to start the game
  shout:
    usage: /shout <message>
    description: command for public chat between teams while game is running
    permission: shout.do
    permission-message: you do not have permission to shout (try /say instead)
  unregister:
    usage: /unregister
    description: Unregister from the game
    permission: unregister.do
    permission-message: you do not have permission to do this
  endgame:
    usage: /endgame
    description: Ends a running game
    permission: endgame.do
    permission-message: You do not have permission to do this




